### PR TITLE
fix: support zustand@4.3.x

### LINKED ISSUE #62: zundo@2.0.0-beta.8 incompatible with zustand@v4.3.x
## Reproduction / Severity

At the moment, when you install `zundo@2.0.0-beta.8` and have the following in your package.json:

```json
"zustand": "^4.0.0"
```

Then Zustand will automatically update to [`4.3.1`](https://www.npmjs.com/package/zustand?activeTab=versions) (because of the caret `^`), resulting in this error:

```
TypeError: (0 , import_vanilla.default) is not a function
index.js?46cb:334 Uncaught TypeError: (0 , import_vanilla.default) is not a function
    at createVanillaTemporal (file:///..../node_modules/zundo/dist/index.js:46:37)
```

## Workaround

I figured out that only **zustand `v4.3.0`/`v4.3.1`** is causing this issue. Downgrading to `npm install zustand@4.2.0` will work as expected.

## Debugging

When exploring the compiled `node_modules/zundo/dist/index.js` file I `console.log` the import statement of `zustand/vanilla`:

```javascript
[...]

// src/temporal.ts
var import_vanilla = __toESM(require("zustand/vanilla"));
console.log(import_vanilla)

var createVanillaTemporal = (userSet, userGet, baseOptions) => {
[...]
```

Which prints the following output:

```
{
  default: {
    createStore: [Function: createStore],
    default: [Function: vanilla]
  },
  createStore: [Getter]
}
```

### PR DESCRIPTION
**Pull request by BrunnerLivio**
fixes #62

I am honestly new to Zundo (I just downloaded it 1 hour ago) and also not really an expert when it comes to Zustand as well 😅 
The [changelogs](https://github.com/pmndrs/zustand/compare/v4.2.0...v4.3.0) are quite insightful if you wanna double check things. Though really unexpected changes for a supposedly "minor" release...

I was able to make the tests all green without major modifications and I quickly double checked whether it works in my application via `npm link` and it works all fine. Though I use Zundo in its most basic form so maybe you need to double check the more advanced usecase of this lib

### CODE REVIEW

**Comment by charkour** [comment]
I'll get to this in about 3 hours. Thank you so much for the PR!

File: packages/zundo/src/index.ts [hunk 1]
```diff
@@ -28,9 +28,9 @@ declare module 'zustand/vanilla' {
 }
 
 type ZundoImpl = <TState>(
-  config: PopArgument<StateCreator<TState, [], []>>,
+  config: StateCreator<TState, [], []>,
   options: ZundoOptions<TState>,
-) => PopArgument<StateCreator<TState, [], []>>;
+) => StateCreator<TState, [], []>;
```
Comment (charkour) [inline packages/zundo/src/index.ts:33]: Can you explain this change here?

Comment (charkour) [reply packages/zundo/src/index.ts:33]: I see here that this is actually not needed. Thanks!

https://github.com/pmndrs/zustand/pull/1373

**Review by charkour — APPROVED** [review]
Looks good. Thanks for the fix! Wasn't expecting zustand v4.3.0 to break this much
